### ISSUE TITLE
Warning for the PacketPlayINAbilities

### ISSUE THREAD

**Issue by retrooper** [artemisac/Artemis-Packet-API#2]
I wouldn't really say this is an issue.
Just I wanted to give out a warning.

I saw the wrapper for the packet PacketPlayInAbilities looked like this:
https://github.com/artemisac/Artemis-Packet-API/blob/master/src/main/java/cc/ghast/packet/wrapper/packet/play/client/PacketPlayClientAbilities.java

Everything is fine.
Just I think I remember you claiming 1.16 support.
If I am false, my bad, this is just a warning.
If I am correct, I recommend fixing this.
1.16 PacketPlayInAbilities only sends the isFlying field.
The other fields have been removed.
(Atleast NMS displays it so)
In the NMS wrappers, they only provide the isFlying field, so I am assuming the other fields got removed and are NOT sent at all.
1.15 is just fine.
Your PacketPlayClientAbilities wrapper should work for 1.7.10->1.15.x, but 1.16.x will fail.

**Comment by terminalsin** [comment]
Resolved in #4. Thank you!
